import { 
  Document, Packer, Paragraph, TextRun, 
  HeadingLevel, AlignmentType, Header, 
  Footer, PageNumber, PageBreak,
  TableOfContents, SectionType,
  ExternalHyperlink, UnderlineType
} from 'docx';
import { Blueprint } from '../../../types';
import { BaseGenerator, ExportOptions } from './BaseGenerator';

export class BusinessPlanGenerator extends BaseGenerator {
  async generate(blueprint: Blueprint, options?: ExportOptions): Promise<Blob> {
    const doc = new Document({
      title: `${blueprint.name} - Business Plan`,
      description: `Comprehensive Business Plan for ${blueprint.name}`,
      sections: [
        // Cover Page
        {
          properties: { type: SectionType.NEXT_PAGE },
          children: [
            new Paragraph({ text: "", spacing: { before: 2000 } }),
            new Paragraph({
              text: blueprint.name.toUpperCase(),
              heading: HeadingLevel.TITLE,
              alignment: AlignmentType.CENTER,
            }),
            new Paragraph({
              text: blueprint.tagline,
              heading: HeadingLevel.HEADING_2,
              alignment: AlignmentType.CENTER,
              spacing: { before: 400 },
            }),
            new Paragraph({ text: "", spacing: { before: 4000 } }),
            new Paragraph({
              text: "OFFICIAL BUSINESS PLAN",
              alignment: AlignmentType.CENTER,
              spacing: { before: 400 },
            }),
            new Paragraph({
              text: new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }),
              alignment: AlignmentType.CENTER,
            }),
            new Paragraph({ text: "", spacing: { before: 2000 } }),
            new Paragraph({
              children: [
                new TextRun({ text: "Generated by ", color: "666666" }),
                new TextRun({ text: "AutoThinker X Venture OS", bold: true, color: "4f46e5" }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
        },
        // Main Content
        {
          properties: { type: SectionType.NEXT_PAGE },
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({ text: blueprint.name, bold: true, size: 18, color: "4f46e5" }),
                  ],
                  alignment: AlignmentType.RIGHT,
                }),
              ],
            }),
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({ text: "Page " }),
                    new TextRun({ children: [PageNumber.CURRENT] }),
                    new TextRun({ text: " | Confidential - AutoThinker X" }),
                  ],
                  alignment: AlignmentType.CENTER,
                }),
              ],
            }),
          },
          children: [
            new Paragraph({
              text: "1. EXECUTIVE SUMMARY",
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400, after: 400 },
            }),
            new Paragraph({
              children: [new TextRun({ text: blueprint.pitch, size: 24 })],
              spacing: { after: 400 },
            }),
            
            new Paragraph({ text: "1.1 Mission", heading: HeadingLevel.HEADING_2 }),
            new Paragraph({ text: blueprint.overview.mission, spacing: { after: 200 } }),
            
            new Paragraph({ text: "1.2 Vision", heading: HeadingLevel.HEADING_2 }),
            new Paragraph({ text: blueprint.overview.vision, spacing: { after: 200 } }),

            new Paragraph({ text: "2. PROBLEM & SOLUTION", heading: HeadingLevel.HEADING_1, spacing: { before: 400 } }),
            new Paragraph({ text: "2.1 The Problem", heading: HeadingLevel.HEADING_2 }),
            new Paragraph({ text: blueprint.overview.problem, spacing: { after: 200 } }),
            
            new Paragraph({ text: "2.2 Our Solution", heading: HeadingLevel.HEADING_2 }),
            new Paragraph({ text: blueprint.overview.solution, spacing: { after: 200 } }),

            new Paragraph({ children: [new PageBreak()] }),

            new Paragraph({ text: "3. MARKET ANALYSIS", heading: HeadingLevel.HEADING_1 }),
            new Paragraph({
              children: [
                new TextRun({ text: "TAM (Total Addressable Market): ", bold: true }),
                new TextRun(blueprint.market.tam),
              ],
              spacing: { before: 200 },
            }),
            new Paragraph({
              children: [
                new TextRun({ text: "SAM (Serviceable Addressable Market): ", bold: true }),
                new TextRun(blueprint.market.sam),
              ],
            }),
            new Paragraph({
              children: [
                new TextRun({ text: "SOM (Serviceable Obtainable Market): ", bold: true }),
                new TextRun(blueprint.market.som),
              ],
            }),

            new Paragraph({ text: "4. TECHNOLOGY ARCHITECTURE", heading: HeadingLevel.HEADING_1, spacing: { before: 400 } }),
            new Paragraph({ text: `Frontend: ${blueprint.technology.frontend}` }),
            new Paragraph({ text: `Backend: ${blueprint.technology.backend}` }),
            new Paragraph({ text: `Database: ${blueprint.technology.database}` }),
            new Paragraph({ text: `AI Stack: ${blueprint.technology.ai_stack}` }),
            new Paragraph({ text: `Deployment: ${blueprint.technology.deployment}` }),

            new Paragraph({ text: "5. EXECUTION ROADMAP", heading: HeadingLevel.HEADING_1, spacing: { before: 400 } }),
            ...blueprint.roadmap.flatMap(phase => [
              new Paragraph({ text: phase.phase, heading: HeadingLevel.HEADING_2, spacing: { before: 200 } }),
              ...phase.tasks.map(task => new Paragraph({ text: `• ${task}`, bullet: { level: 0 } }))
            ]),
          ],
        },
      ],
    });

    return await Packer.toBlob(doc);
  }
}
