import { Blueprint } from '../../../types';
import { BaseGenerator, ExportOptions } from './BaseGenerator';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export class ExecutiveSummaryGenerator extends BaseGenerator {
  async generate(blueprint: Blueprint, options?: ExportOptions): Promise<Blob> {
    const doc = new jsPDF();
    const color = this.getBrandingColor(blueprint.branding);
    
    // COVER PAGE
    doc.setFillColor(color);
    doc.rect(0, 0, 210, 297, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(40);
    doc.setFont('helvetica', 'bold');
    doc.text(blueprint.name.toUpperCase(), 105, 100, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(blueprint.tagline, 105, 115, { align: 'center' });
    
    doc.setFontSize(12);
    doc.text('INVESTOR EXECUTIVE SUMMARY', 105, 200, { align: 'center' });
    doc.text(new Date().toLocaleDateString(), 105, 210, { align: 'center' });
    
    doc.addPage();
    
    // HEADER (Page 2+)
    doc.setFillColor(color);
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.text(blueprint.name, 15, 13);
    doc.text('Confidential Investor Document', 195, 13, { align: 'right' });

    // CONTENT
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('EXECUTIVE SUMMARY', 15, 40);
    
    doc.setDrawColor(color);
    doc.setLineWidth(1.5);
    doc.line(15, 45, 80, 45);
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    const splitPitch = doc.splitTextToSize(blueprint.pitch, 180);
    doc.text(splitPitch, 15, 55);
    
    let y = 55 + (splitPitch.length * 7);
    
    // Key Highlights Table
    autoTable(doc, {
      startY: y + 10,
      head: [['Venture Intelligence', 'Strategic Overview']],
      body: [
        ['Problem Statement', blueprint.overview.problem],
        ['Core Solution', blueprint.overview.solution],
        ['Market Potential (TAM)', blueprint.market.tam],
        ['Target Customer (ICP)', blueprint.customers.icp],
        ['Revenue Model', blueprint.finance.revenue_streams.join(', ')],
        ['Technical Stack', `${blueprint.technology.frontend} / ${blueprint.technology.backend}`],
      ],
      headStyles: { fillColor: color, fontSize: 12, fontStyle: 'bold' },
      bodyStyles: { fontSize: 10 },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
      theme: 'grid'
    });
    
    // FOOTER
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 2; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(`Generated by AutoThinker X | Page ${i}`, 105, 285, { align: 'center' });
    }

    return doc.output('blob');
  }
}
